### ISSUE TITLE
Warn against flashing Windows images

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1035]
A lot of users are constantly trying to flash Windows images, which will not work on Etcher given that Windows images require special treatment.

As a solution, let's develop a regex (or collection of regexes) based on all the Windows images file names [available from MSDN](https://msdn.microsoft.com/subscriptions/securedownloads/?#searchTerm=windows&ProductFamilyId=0&Languages=en&FileExtensions=.img,.iso&PageSize=10&PageIndex=0&FileId=0) and use that to show a warning.

See https://github.com/resin-io/etcher/issues/210 for the issue tracking Windows support.

**Comment by lurch** [comment]
Is there a version of that page (or similar) that's viewable without needing a Microsoft login?

**Comment by jviotti** [comment]
I don't think so :(

**Comment by alexandrosm** [comment]
Can we just show a simple warning if the image has the "windows" word in
it? If some other equivalently simple pattern exists in the names, maybe
let's use that, but keep it overall very simple, rather than some
aggressive regex?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by fhdk** [comment]
> Is there a version of that page (or similar) that's viewable without needing a Microsoft login?
@lurch I can generate a copy for you
