### ISSUE TITLE
Identity partition table type in analytics & error reporting

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1116]
I'd be great if we can know in advance if an image has a MBR or a GPT.

**Comment by lurch** [comment]
If we're gathering this info for analytics purposes, it might also be useful to collect which filesystems are being used in the images being written? (FAT16/FAT32/exFAT/ext3/ext4/btrfs/etc.)

I'll assign this to @jhermsmeier because he already has modules to do some of this, but I dunno what priority this task has.

**Comment by jhermsmeier** [comment]
Closed in https://github.com/resin-io/etcher/pull/1248

**Comment by lurch** [comment]
Apologies if I'm being dense, but what part of #1248 closes this? All I can see is
`analytics.logEvent('Missing partition table', image);`

**Comment by jhermsmeier** [comment]
The image metadata gets logged, which is what contains the MBR/GPT info

**Comment by lurch** [comment]
Ah, thanks. Does this also include the partition / filesystem types, as I mentioned in my comment above?

**Comment by jhermsmeier** [comment]
Yup it does
