### ISSUE TITLE
Fix errors when unplugging a drive exactly when the drive scanning script runs

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1126]
Steps to reproduce:

- Unplug a drive *exactly* when the drive scanning script is running

You might want to add `console.log` above https://github.com/resin-io/etcher/blob/master/lib/gui/modules/drive-scanner.js#L41 to know when exactly the script is running,  or decrease the drive scanning interval to increase the chances: https://github.com/resin-io/etcher/blob/master/lib/gui/modules/drive-scanner.js#L36

This is the error I get:

<img width="460" alt="screenshot 2017-02-21 17 14 45" src="https://cloud.githubusercontent.com/assets/2192773/23188147/0a44bade-f864-11e6-9b44-04f69ff70fc8.png">

**Comment by jviotti** [comment]
I confirm this issue only happens in OS X. I can't reproduce on GNU/Linux nor Windows.

**Comment by lurch** [comment]
This is probably highly timing-dependent, so maybe it's just harder to reproduce on other platforms?
All the drivelist platform-scripts effectively do:
```
drives = list_drives()
foreach drive in drives:
    get_more_info(drive)
```
so it's conceivable that _any_ of the scripts would fail if a drive disappears between `list_drives` and `get_more_info`.
In fact I just tried on Linux `lsblk -b -d "/dev/sdd" --output SIZE,RO,RM,MODEL` (I don't have any `/dev/sdd` currently) and it errored with `lsblk: /dev/sdd: not a block device` and set exit-code 1.

Maybe this is something that should be handled at the `drivelist` level (i.e. making all the scripts robust to drives disappearing between `list_drives` and `get_more_info`), rather than letting the error bubble up to Etcher itself?
(and of course if there are multiple steps in the `get_more_info` process, then the drive could potentially disappear between any of those steps - which I guess means we'd need to internally buffer the info (as we're gathering it for each drive), rather than just printing directly to STDOUT)

**Comment by jviotti** [comment]
Yeah, maybe. I've tried reproducing this for a good while without success, but you might be right in that it may be just harder to reproduce in other platforms.

**Comment by jviotti** [comment]
> Maybe this is something that should be handled at the drivelist level (i.e. making all the scripts robust to drives disappearing between list_drives and get_more_info), rather than letting the error bubble up to Etcher itself?

Sounds like the way to go!

**Comment by lurch** [comment]
>  I've tried reproducing this for a good while without success

I guess a easy way to 'force' that would be to just put a big `sleep 10` between the `list_drives` and `get_more_info` steps ;-)

**Comment by jviotti** [comment]
That's a good idea. Turns out there were errors on Windows:

```
C:\cygwin64\home\jviotti\Projects\etcher\node_modules\drivelist\scripts\win32.bat?.wsf(79, 3) (null): 0x80041002
```

However the script exits with code 0, and since the output is invalid YAML, it gets only printed to DevTools instead of showing an error alert, which explains why I've not been seeing it.

The weird thing is that if I execute the script directly (from `cmd.exe`), then it exists with code 1, so `drivelist` should be catching this :/

**Comment by jviotti** [comment]
OK, so we were not passing the VBScript exit code to the caller from within the `.bat` wrapper. I'll send a PR to `drivelist` in a minute. This is what I get after my changes:

![capture](https://cloud.githubusercontent.com/assets/2192773/23268726/f604fc84-f9c4-11e6-8843-b2f91f03ca01.PNG)

**Comment by jviotti** [comment]
See https://github.com/resin-io-modules/drivelist/pull/146

**Comment by jviotti** [comment]
Adding a timeout, as @lurch suggested, revealed the following on Linux:

<img width="583" alt="screenshot 2017-02-23 14 47 36" src="https://cloud.githubusercontent.com/assets/2192773/23273902/2ae1dbfe-f9d7-11e6-96e8-2955217bd230.png">
