### ISSUE TITLE
Partition Support

### ISSUE THREAD

**Issue by ProteusBlue** [resin-io/etcher#1317]
- **Etcher version:** Any version
- **Operating system and architecture:** Any
- **Do you see any meaningful error information on DevTools?** N/A

I have noticed that Etcher does not allow the user to burn images to partitions of the internal disk(eg. I have two partitions, one is Macintosh and the other Ubuntu, I am trying to burn to Ubuntu). I feel like this feature should be added, because some users don't have flash drives, DVDS, and such.

**Comment by jviotti** [comment]
Hi @ProteusBlue ,

Thanks for reporting. The way that Etcher works is that it copies an image byte by byte to the drive, without doing any manipulation to it. The result is that the partition table from the image is copied as-is to the drive. Allowing to flash an image to a partition means completely changing the way that Etcher works (working on a file level rather than on an image level), and somehow manipulate both the input image and the output drive partition tables to accommodate images with multiple partitions.

We have https://github.com/resin-io/etcher/issues/453 to track this, but I can't give any estimation for it, given its not a high priority for Etcher at the moment.
