### ISSUE TITLE
USB image hangs on boot with old AMIBIOS 1.21.11

### ISSUE THREAD

**Issue by isness** [resin-io/etcher#1474]
I've got an old ECS K7S5A motherboard with AMIBIOS 1.21.11 and USB 1.1. I successfully create USB image with Etcher, but trying to boot this system fails. Altough it succeeds in finding the USB drive and boot sector, it hangs immediately after that. There is no USB stick read/write activity. The only program that works with this kind of systems is YUMI 2.0.4.8. 

- **Etcher version:** 1.0.0
- **Operating system and architecture:** Ubuntu Gnome 17.04 64-bit (used to create image); LXLE Desktop 16.04.2 32-bit (on the target machine)
- **Image flashed:** LXLE Desktop 16.04.2 32-bit.
- **Do you see any meaningful error information in the DevTools?** No.

![20170526_082557](https://cloud.githubusercontent.com/assets/1119172/26482007/658164f6-41ed-11e7-888b-0aeb7b4b1adb.jpg)

**Comment by jviotti** [comment]
Hi @isness ,

Etcher is an image flasher, and simply copies whatever you give it byte by byte to the drive, without inspecting nor manipulating the contents.

If the image fails to boot, then it might be a problem with the image, the device, or because the image requires some extra special treatment to be bootable (maybe worth double checking in the instructions?)
