### ISSUE TITLE
Implement a new file / source picker

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1823]
Instead of a file picker, have a modal with 3 options:
  - type url
  - duplicate whole source
  - select file from source

If "select file" is preferred, show a very simple HTML file picker.
Also investigate the need for an on-screen keyboard for typing URLs (add to resin-electronjs?)

**Comment by Shou** [comment]
Instead of a modal should we make it a page and move towards the V2 design? This also comes with the added benefit of allowing me to write it in React so we don't get more Angular into the codebase.

@konmouz could we get a mockup of the image selection screen with URL inputs and drive selection? We could potentially reuse the drive modal here if needed and just have a "select drive" button, if you feel like that's better. Also based on the V2 design I assume we want the recent selections in there too.

**Comment by konmouz** [comment]
@Shou I'll take care of that within this or next week.

**Comment by Shou** [comment]
Awesome.

**Comment by lurch** [comment]
Sounds like this'd be a great place for closer interaction with https://github.com/resin-io-modules/resin-components ?

**Comment by Shou** [comment]
@konmouz what's the status on this now?

**Comment by konmouz** [comment]
@Shou I can push this and deliver today

**Comment by jhermsmeier** [comment]
Duplicate of #950

**Comment by curcuz** [comment]
ping @konmouz - any news?

**Comment by konmouz** [comment]
@curcuz I need to redesign this and add some features but should be ready soon
