### ISSUE TITLE
Is it really neccesary to have a 210mb program?

### ISSUE THREAD

**Issue by TomJansen** [resin-io/etcher#1887]
Hello! This program is great! I only have one issue, this program is around 200mb. Is this really necessary?
The same result really can be had with  `dd bs=4M if=2017-09-07-raspbian-stretch.img of=/dev/sdX` Now I know, the UI is really nice, but to be fair, it feels kind of bloated.

**Comment by lurch** [comment]
A lot of that overhead comes from us using https://electronjs.org/

Although Etcher _appears_ simple, that's deliberate and it actually hides a lot of complexity under the hood, in order to make it so easy to use and so robust.

There are many features that Etcher supports that `dd` doesn't, e.g. warning if the input image is larger than the output drive, preventing you writing to your system drives by default, transparently decompressing images, validating the written data, etc. etc.
And there's more features to come too :) https://resin.io/blog/the-future-of-etcher/
