### ISSUE TITLE
Size problemem

### ISSUE THREAD

**Issue by neilyoung** [resin-io/etcher#2004]
- **Etcher version:** 1.2.1
- **Operating system and architecture:** Mac OSX High Sierra
- **Image flashed:** Backup of a raspbian installation
- **Do you see any meaningful error information in the DevTools?** No, but the error message is self explanatory

I have taken a backup of an Raspbian installation from a 16 G SD card. The image size is 15.986.589.696 bytes. Etcher refuses to flash it to another 16 GB card. The message is 

SD Card Reader  - 15.93 GB
/dev/disk3
Too small for Image

Not sure why 15.93 GB are not sufficient to flash 14.8 GB

Any chance to override this decision?

**Comment by lurch** [comment]
Ahh, this confusion is because some systems use 1GB = 1,000,000,000 bytes, and other systems use 1GB = 1,073,741,824 bytes (see https://en.wikipedia.org/wiki/Gigabyte for more info).

So it looks like in your case that your SD Card is 15.93 GB but your image is actually 15.99 GB (i.e. your image is bigger than your SD card).
Unfortunately there's not much standardisation in SD card sizes, and a "16 GB" card from one manufacturer may actually be quite a bit smaller or larger than a "16 GB" card from another manufacturer (or even a different model from the same manufacturer).
