### ISSUE TITLE
Eliminating popup asking to format disk on etcher

### ISSUE THREAD

**Issue by aamm132** [resin-io/etcher#2024]
- **Etcher version: 1.3.1** 
- **Operating system and architecture: Windows** 

I just recently built etcher locally and can make my changes I need to on my machine. One thing I have been looking to want to change is the popup that appears frequently whenever an image is being flashed to a drive. The popup tells you that you need to format the disk first. Regardless of accepting to format it or not, the flashing process continues successfully anyway. Is there any possibility that this popup can be removed/prevented?

**Comment by lurch** [comment]
This popup is coming from Windows itself (it's getting "upset" that it can't read any filesystems on the drive), so no there's nothing we can do (currently) to prevent it.

Longer-term, we plan to do native drive-locking, so that Etcher will be able to grab exclusive access to the drive, and (I think) Windows wouldn't then ask you to format it. However this relies on a feature that's only recently been added to NodeJS, and we need to wait for that version of NodeJS to be incorporated into Electron, before we can then add this drive-locking functionality to Etcher.

**Comment by deng1604** [comment]
![Uploading image.png…]()
该如何应对?
