### ISSUE TITLE
Insufficient Space (there's plenty of space)

### ISSUE THREAD

**Issue by Kazom** [resin-io/etcher#2452]
- **Etcher version: 1.4.4** 
- **Operating system and architecture: macOS High Sierra** 
- **ai-homekit-camera.** 

Trying to install ai HomeKit camera a 2.48 GB dmg file onto my (completely free) 16 GB microsd Card. Etcher tells me there's insufficient space (there's not). After I select the dmg file either shows it as over 16 gigs which is where it is reading wrong. I'm not sure why it's choosing to assign its own storage size to the dmg.
 **To be clear the dmg expanded is nowhere near 16 GB as soon as you select it in etcher it think's it's an even bigger size**

![screen shot 2018-08-17 at 1 52 30 pm](https://user-images.githubusercontent.com/16228916/44283734-ecca3f80-a224-11e8-93d5-ad7e634fa57e.png)

![screen shot 2018-08-17 at 1 52 18 pm](https://user-images.githubusercontent.com/16228916/44283700-dd4af680-a224-11e8-8d7f-048fe5bd7011.png)
![screen shot 2018-08-17 at 1 52 48 pm](https://user-images.githubusercontent.com/16228916/44283704-e1771400-a224-11e8-93c5-4598f71f6b01.png)

**Comment by lurch** [comment]
Doing a quick google, I guess you're following the tutorial at https://appleinsider.com/articles/18/03/21/how-to-create-your-own-homekit-camera-with-a-raspberry-pi-and-homebridge ? Even that article says "16GB or larger micro SD card" even though the downloaded DMG file is 'only' 2.48 GB.
AIUI, a DMG can contain a full partition table, so it looks like the "16 GB" SD card that the DMG was created from is slightly larger (i.e. by 94MB) than the "16 GB" SD card that you're trying to write to. Unfortunately a "16GB" card from one manufacturer will be a different size to a "16GB" card from a different manufacturer :confused:   (You can see in the Etcher screenshot in the AppleInsider tutorial that they're using a 16.03 GB SD card)  The reason that the downloaded DMG is so small in comparison, is that a lot of that 16 GB will simply be empty space.

So AFAICT your only options are either to try a 16 GB SD card from a different manufacturer (in the hope that it's a little bit bigger) or to use a 32 GB SD card (as that will _definitely_ be big enough!)
The more advanced option would be to resize the partitions inside the DMG so that they're small enough to fit on _your_ 16 GB SD card, but I don't have a Mac myself so dunno how to do that for DMG files.

Ahh, seems other people have also run into the same problem with this particular image: https://forums.appleinsider.com/discussion/204720/how-to-create-your-own-homekit-camera-with-a-raspberry-pi-and-homebridge/p2
(i.e. it's a 'problem' with the image, not a problem with Etcher)
