### ISSUE TITLE
Set minimum window size on Linux

### ISSUE THREAD

**Issue by danrabbit** [resin-io/etcher#272]
It looks like there isn't any minimum window size. You can pretty easily make the app look bad by resizing the window too small

![screenshot from 2016-04-09 23 19 07](https://cloud.githubusercontent.com/assets/7277719/14408437/a2d5a584-fea9-11e5-8c0a-2645598ef055.png)

**Comment by jviotti** [comment]
Hi @danrabbit 

Thanks for reporting this. We are setting `resizable: false` in the `BrowserWindow`. After some more investigation, turns out there was a known issue in Electron where the window was resizable on GNU/Linux even when passing `resizable: false`. I upgraded to the Electron version containing the fix.

Thanks you very much again!

**Comment by danrabbit** [comment]
Thank you for the very speedy response!
