### ISSUE TITLE
Application doesn't have permission or ask for password to use application on default Linux Xubuntu 14.04

### ISSUE THREAD

**Issue by gameslayer** [resin-io/etcher#412]
This isn't a big deal for me but for new users mainly by default this application cannot work unless you open the terminal and either run it with sudo -s or gksu being the best easiest quick fix to ask for the a password to run the software, maybe it should have this added into the shortcut it makes depending on the distro so it does "Works for everyone, no more complicated install instructions."

**Comment by leillo1975** [comment]
Have the same problem in Ubuntu 16.04 64Bits. I made a workaround:
1. Install "Main Menu" (alacarte) 
2. Search Etcher in the menu elements
3. Edit Etcher in properties and write "gksudo" before command
4. Now when a select Etcher in Dash (or menu), it prompt me to introduce my sudo password

**Comment by jviotti** [comment]
Hey there,

Thanks for the suggestions. We're working on solving the root cause of this problem, which is only elevating the forked process that actually performs the writing. I'm locally baking a commit to implement this (I have it working already, but needs some polishing).

I'll hopefully release it in the later version, stay tuned!

**Comment by danrabbit** [comment]
Wanted to make a note that GKSU is deprecated and should not be used as per OP's recommendation. The proper thing to do would be to use [policykit](https://wiki.gnome.org/Projects/PolicyKit)

**Comment by jviotti** [comment]
Hi @danrabbit,  

We'll go with `pkexec` as per your suggestion!

**Comment by gameslayer** [comment]
so what would be the multi distro solution to this to elevation issue

**Comment by jviotti** [comment]
Hi @gameslayer ,

Instead of elevation the complete application at the beginning, which doesn't play nice when executing the app from the Unity launcher for example, we'll only elevate a forked process that performs the writing, for which we can show nice GUI dialogs for all distributions based on `pkexec`.

**Comment by gameslayer** [comment]
@jviotti Sounds great hope it works well multi platform :)

**Comment by jviotti** [comment]
@gameslayer I've did some extensive tests on the Linux machines I could access too and it works fine as long as the user has either `gksudo`, `kdesudo` and `pkexec`. We'll see! I'm publishing a new version in a couple of hours, don't hesitate to ping me if you find an edge case!

**Comment by jviotti** [comment]
Hi @gameslayer ,

Time to give it a go: http://www.etcher.io :D

**Comment by danrabbit** [comment]
I can confirm that the latest version of etcher asks for permission on elementary OS. Good work guys! Might wanna drop the "sudo" line from the directions on the website ;)

**Comment by jviotti** [comment]
Sweet @danrabbit , thanks for the testing, I'll drop the website instructions in a minute :)

**Comment by gameslayer** [comment]
Problem is solved with newer version tested on Xubuntu.
