### ISSUE TITLE
Unable to select drive after selecting image. Problem with UI.

### ISSUE THREAD

**Issue by henader** [resin-io/etcher#418]
Right after launching Etcher looks like this:

![2016-05-18](https://cloud.githubusercontent.com/assets/12104868/15353792/f72e16ac-1cea-11e6-9ab0-bee2024f72f3.png)

Then whe I select an ISO (in this case Windows 10) it does something weird with UI:
![2016-05-18 1](https://cloud.githubusercontent.com/assets/12104868/15353830/2d16333a-1ceb-11e6-935b-ce44b30ce41b.png)

Is looks like the problem with UI, because if I select an ISO with shorter name I get different reults. Example:
![2016-05-18 2](https://cloud.githubusercontent.com/assets/12104868/15353865/5718dd0e-1ceb-11e6-85f9-0ce2fc60c4b9.png)

**Comment by jviotti** [comment]
Hi @henader ,

Thanks a lot for raising this, I guess we never considered the possibility of such a long file name :)

Its still not very clear to me what would be the ideal solution:

1. Only display X number of characters and show a couple of dots at the end, and potentially show the whole name as a tooltip.

2. Split the name into multiple lines, although breaking a word without spaces looks really bad and confusing, and it still doesn't solve the issue completely -- e.g: if you still have a very long file name, it could still overflow to the bottom.

I'll ping Etcher's designer for some input on this.

**Comment by jsejcksn** [comment]
Since this is still open, I'd like to recommend the former idea, but instead of terminating the preview name with an ellipsis, show an ellipsis in the middle of it. For example, if you decide that the file name preview is 30 characters:

Original
```
pl_windows_7_home_premium_with_sp1_x64_dvd_u_676540.iso
```

Ok
```
pl_windows_7_home_premium_with...
```

More useful (shows extension)
```
pl_windows_7_home_premium_....iso
```

Even more useful (shows last half of file name, too)
```
pl_windows_7_ho...vd_u_676540.iso
```

**Comment by jviotti** [comment]
Hi @jsejcksn,

Sounds like a good idea! We're currently discussing this, and looks like we'll go with your suggestion plus a small label that you can click to show the full file name,

**Comment by jviotti** [comment]
Design sketches:

![screen shot 2016-05-18 at 4 37 49 pm](https://cloud.githubusercontent.com/assets/2192773/15365084/eb2b6e52-1cec-11e6-8604-d80347504e81.png)
![screen shot 2016-05-18 at 5 26 59 pm](https://cloud.githubusercontent.com/assets/2192773/15365090/ef64daf8-1cec-11e6-8d92-d10e75edca73.png)

**Comment by henader** [comment]
Looks like a good solution. Just a minor thing: if the filename is wider then the preview-box I think it will be ok to multiline it without mercy.

**Comment by jsejcksn** [comment]
@jviotti Looks good, except that the label looks a little like it's "pointing" to Select Drive because it's centered and because of its position relative to the top of the circle around step 2. Perhaps you could move it from the center to above the truncated filename with an actual tooltip arrow:

![tooltip-example](https://cloud.githubusercontent.com/assets/868251/15366976/81918cf6-1cec-11e6-8f5c-3847f267b224.png)

**Comment by jviotti** [comment]
Hi @henader @jsejcksn 

Thanks a lot of the awesome feedback. Some way to make it clearer that the modal refers to the image would be nice.

/cc @taahirisaacs

**Comment by jviotti** [comment]
I've implemented this fix with the centred modal (instead of above a step) for simplicity, and we can't take it from there afterwards!
