### ISSUE TITLE
How to select two or more driver?

### ISSUE THREAD

**Issue by Pillar1989** [resin-io/etcher#477]
I want to burn the image to two or more driver at same time. how can I do ?

**Comment by jviotti** [comment]
Hey there @Pillar1989 ,

We don't have support from this in Etcher itself yet (we have an opened issue for it here: https://github.com/resin-io/etcher/issues/267).

I've played around with a prototype not long ago, but it was far from ready, since it was causing sporadic OS X kernel panics and other issues in other operating systems.

This is something we're going to be working very soon, so stay tuned and keep an eye on the issue I've linked to above!
