### ISSUE TITLE
Too many drives - list inaccessible.

### ISSUE THREAD

**Issue by AlexAtkinson** [resin-io/etcher#789]
- 0.36.8.0
- Windows 10 (updated), x64
- If more than a few drives, the drive list extends outside the parent window, making it inaccessible. Using the dev tools I adjust the .dropdown-menu font-size to 7px to get around this. Please fix.

**Comment by jviotti** [comment]
Hey there!

After some discussion, we think you might be running a really old Etcher version, where we previously used a dropdown instead of the drive selector widget you see in the screenshot above, so the best way to go would be to upgrade Etcher.

See https://github.com/resin-io/etcher/issues/202

![45bfab88-e6bc-11e5-8c2a-c53560732d37](https://cloud.githubusercontent.com/assets/2192773/20435208/25d1ce74-ada3-11e6-8fda-a873b44bb7ca.png)


Please re-open if this is not the case!
