### ISSUE TITLE
Make meaning clear of "connect a drive" text when no drives are found

### ISSUE THREAD

**Issue by WasabiFan** [resin-io/etcher#884]
- **Etcher version:** Beta 15, 16
- **Operating system and architecture:** Windows 10 64-bit
- **Do you see any meaningful error information on DevTools?** N/A

When you don't have a drive connected, Etcher looks like this:

![image](https://cloud.githubusercontent.com/assets/3310349/20459891/0215bb82-ae87-11e6-83e5-dc2b019c396f.png)

Once you connect one, that changes to this:

![image](https://cloud.githubusercontent.com/assets/3310349/20459896/3fd7b9f2-ae87-11e6-9cdc-bd956a11d1d8.png)

Not only is the first one unclear -- I can't tell what I am actually supposed to do there -- but it barely changes once you have things connected. I think that the "no drives connected" state should be changed to make the lack of drives clear and to make the rectangle look less like a button.

**Comment by WasabiFan** [comment]
Interesting... it looks like this was a regression since beta 7, when the rectangle was red while no drives were available. I don't think that the old behavior was optimal, but it was better than it is now.

**Comment by jviotti** [comment]
Yeah, we should definitely get this fixed for once and for all. @taahirisaacs , @konmouz mind giving us a way forward here?

**Comment by lurch** [comment]
It's also been niggling me slightly that the `Change` buttons (for both Image and Drive) look nothing like buttons; but I dunno if that's something that needs "fixing" or not...

**Comment by konmouz** [comment]
Please check [here](https://github.com/resin-io/etcher/issues/888) regarding 'connect a drive' issue.

**Comment by konmouz** [comment]
@Shou @jviotti, we still have the issue with 'connect a drive' on the latest version. This looks like a CTA while it is just a message. Ideally, this message appears within the drives' modal window (screenprint from Zeplin). If this is tricky, 'connect a drive' should have an orange background instead of blue.

<img width="923" alt="screen shot 2017-02-27 at 16 51 41" src="https://cloud.githubusercontent.com/assets/15323961/23370639/458c61b6-fd0d-11e6-8efd-1278b8f7fb96.png">

**Comment by jviotti** [comment]
Yeah, let's make the current dialog open by default if there is no drive and keep improving from there. /cc @Shou

**Comment by Shou** [comment]
So to clarify we open the drive selector modal on startup and display the message there if there is no drive?

**Comment by lurch** [comment]
No, I think automatically opening the drive-selector modal on startup would confuse / scare people.

**Comment by jviotti** [comment]
OK, I'm really confused now :P As far as I understand, @konmouz proposal is to show the drive selector automatically once you select the image, even if there are no drives (e.g: we show an empty drive selector), thus completely covering the "Connect a drive" button, making it unnecessary.

**Comment by konmouz** [comment]
Yes, my proposal is to automatically open the drives' modal except if there is only one drive, so it will be automatically selected. If you think this is too aggressive, instead of 'connect drive' we could have the actual button 'select drive' and user can open the modal manual. Again, if there is only one drive, it will be automatically selected.

**Comment by Shou** [comment]
Maybe we can do both for convenience here—orange to show that there's no drive but also allow the user to open the dialog or something to that effect? I think not having an indicator right there on the main page is a tiny step backwards. My idea is that it should get the least in the way of the user, because sometimes they may want to see whether there's a drive before clicking it, but also allow users to open the drive selector dialog in preparation before they connect their drives.

Either way I'll push some changes to a branch any moment now.

**Comment by Shou** [comment]
Here we go.

**Comment by lurch** [comment]
Yeah, perhaps it's just me, but I think automatically opening any modal (except for the update-available notification) as soon as the application starts up, without any other user-interaction first, feels a bit aggressive. IMVHO. Especially as the current "flow" is to select an image first, not select a drive first.

.....

Ah! I now see that I missed the "once you select the image" part of @jviotti 's last comment ;-)  But I guess if we do open the drive-selection modal automatically as soon as an image has been selected, maybe it makes Etcher feel a bit like an "installation wizard" type program rather than a typical desktop application? \*shrug\*
