### ISSUE TITLE
Make behavior of protected system drives more obvious to user

### ISSUE THREAD

**Issue by WasabiFan** [resin-io/etcher#888]
This came out of a discussion on Gitter, but I wanted to materialize it here for tracking.

> @alexandrosm: @WasabiFan in general I wonder if instead of not showing system drives at all, instead Etcher should just not auto-select them, de-emphasise them on the selection menu, and if the user actively selects it, it gives a warning, but ultimately goes ahead.
@alexandrosm: in other words treat the system drive heuristic as a heuristic instead of as a law as it does now

> @WasabiFan: Yeah, I like that. Or maybe gray them out and then put the "unsafe mode" checkbox on the selection screen (something like "Allow selection of system drives").
This would make it much easier for users to understand why their drives aren't showing up.

In general, the idea would be to make the filtering out of "system" drives visible to the user, so that they can see what is being filtered out and why.

**Comment by alexandrosm** [comment]
One more thing to highlight, I like the idea of moving things out of the
"garbage dump" settings page and into the specific screens they are
relevant on. If unsafe mode makes more sense in the drive selection, let's
move it in there.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by WasabiFan** [comment]
Agreed, especially if in doing so that checkbox gets a better name! It would be great to see "settings" become something more like "preferences" (logging, telemetry, debugging, etc.).

**Comment by jviotti** [comment]
Sounds cool. Lets put a "system drive" badge as we do for locked, or small devices, and disable them as well. Once that's done, we can move the checkbox there.

**Comment by lurch** [comment]
Yeah, overlaying badges on different types of drives is also something that we discussed with @taahirisaacs and @konmouz at the [Summit](https://resin.io/blog/summit-2016/). I think we decided that removable drives (that we don't detect as "system") should always be displayed at the top of the list.

IMHO if we're going to be displaying "System" drives to the user (with 'just' a simple tickbox to enable writing to them) then perhaps we also ought to attempt to identify "boot" drives, and **never** allow those to be overwritten? And we could/should also filter "source" drives, as mentioned in #830 

So, there'd then be:
 * Removable drives - always okay to write
 * "System" drives - writable if the user enables "unsafe mode" (or whatever it gets renamed to)
 * "Boot" drives (e.g. where the current Operating System was loaded from - should we also try detecting swap / pagefile drives currently being used?) - we should prevent the user writing to here

And then any of the above drives can also be:
 * "Source" drives where the disk image is currently being read from - we should prevent the user writing to here
 * "Locked" drives (e.g. SD cards with the read-only switch enabled) - non-writable at the hardware level 
 * "Small" drives where the capacity is less than the currently-selected image - should we allow these to be written to in "unsafe mode"?

Any other categories? :)

**Comment by WasabiFan** [comment]
I would recommend avoiding attempting to detect "boot drives". I suspect that Etcher wouldn't be able to do it reliably, and if it isn't reliable I don't think that it should be used at all. For example, on one of my PCs, I had my user folder stored on one drive while the system was on another; applications were stored on the same drive as my user folder. How would this be detected? I'd bet that edge cases like that would render this sort of "protection" unreliable at best and outright dangerous at worst. I'd favor just detecting generic "system" drives and putting protections in place there.

**Comment by alexandrosm** [comment]
we discussed this today with @konmouz in person, and he has some sleek
designs, i suspect he might post them here for further comment

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by konmouz** [comment]
Yes, I will upload soon, I just want to recap with @taahirisaacs to sync the designs.

The idea is that there will be a pill label for system drives (drive selection modal). All drives, including system ones, are always selectable without enabling 'unsafe mode' (this option will be removed). However, if the user selects a system drive, there will be some sort of alert before continuing (also color change of button). In addition, after clicking 'Flash', user will get another alert modal to re-confirm that flashing a system drive is intended. So practically, it is quite impossible to flash a system drive accidentally.

As an advance setting, we could let users deactivate the final alert to speed up the process. However, I don't think that this will be a frequent use case so probably doesn't really worth it.

Finally, the boot drives concept sounds really good. If this can be implemented reliably it would be great.

**Comment by jviotti** [comment]
> IMHO if we're going to be displaying "System" drives to the user (with 'just' a simple tickbox to enable writing to them) then perhaps we also ought to attempt to identify "boot" drives, and never allow those to be overwritten? And we could/should also filter "source" drives, as mentioned in #830

It sounds difficult to get right, but we could get almost there by detecting drives containing partitions mounted at `/`, `/boot`, `/home`, etc in the case of UNIX, and drives containing drive letters that match `%SYSTEMDRIVE%` and `%HOMEPATH%` in Windows.

**Comment by lurch** [comment]
Yeah, that's what I was thinking. And we could also scan `/proc/cmdline` on Linux for `root=`. And possibly also check for `%PROGRAMFILES%` on Windows?

**Comment by jviotti** [comment]
Sounds good. @lurch Do you mind opening a new issue in `drivelist` to track this?

**Comment by lurch** [comment]
Done https://github.com/resin-io-modules/drivelist/issues/126

**Comment by konmouz** [comment]
@taahirisaacs and I had a meeting earlier today, so we end up with the following Ui flow:

State after selecting an image:
- If only one removable drive is connected, it will be automatically selected
- Else, if no removable drive or more than one is connected, 'Browse Drives' CTA will be highlighted

![01](https://cloud.githubusercontent.com/assets/15323961/20760230/53fedf26-b717-11e6-9b32-f33b0923b126.png)

Select drive modal:
- All drives are selectable, however, system drives have a clear label (hopefully boot drives as well)

![02](https://cloud.githubusercontent.com/assets/15323961/20760234/5a7aefa2-b717-11e6-91a7-366ad9ac1f57.png)

Select drive modal:
- If a removable drive is selected, 'Continue' CTA will be highlighted in the usual blue color
- If a system drive is selected, 'Continue' CTA will be highlighted in a red color along with an 'alert' icon and a short confirmation message
- Regarding [double click selection](https://github.com/resin-io/etcher/issues/880#event-876991647), we can implement it only on removable drives

![03](https://cloud.githubusercontent.com/assets/15323961/20760235/5a9e2e54-b717-11e6-8ba2-ebf11c136a57.png)
![04](https://cloud.githubusercontent.com/assets/15323961/20760239/5aa0329e-b717-11e6-892e-983952de04d1.png)

- If a system drive is selected, a small 'alert' icon is placed next to the drive name
- If the drive name or the icon is clicked, a small modal appears containing all the info relevant to the drive

![05](https://cloud.githubusercontent.com/assets/15323961/20760238/5a9f68b4-b717-11e6-81d8-24a1d15901d4.png)
![06](https://cloud.githubusercontent.com/assets/15323961/20760237/5a9f5fae-b717-11e6-810f-ae7f446974ae.png)

Flash:
- If user clicks 'Flash' while a system drive is selected, a new confirmation modal appears displaying the selected drive and double-checking if flashing a system drive is an intended action
- User can confirm flashing or directly change the selected drive

![07](https://cloud.githubusercontent.com/assets/15323961/20760236/5a9e8cfa-b717-11e6-8ab5-3b5c9351304d.png)

**Comment by lurch** [comment]
Looks very nice :grinning:

**Comment by lurch** [comment]
...and WRT #884 , it's not explicitly spelled out above, but if we're always displaying system drives, then I guess the drive-list will **never** be empty (since there'll always be at least one system drive), and so the "connect a drive" button will never appear.

**Comment by jviotti** [comment]
Looks very cool! What about sorting? Should we sort the available drives so that the system one always get below?

**Comment by konmouz** [comment]
@lurch Yes, exactly. System drives are always displayed. Currently, the only case where Etcher selects a drive automatically is when only one removable drive is connected. 'Unsafe mode' has been [completely removed](https://github.com/resin-io/etcher/issues/919) (and therefore advanced settings as well).

@jviotti That would make sense since selecting a removable drive should be more often

**Comment by WasabiFan** [comment]
> the "connect a drive" button will never appear.

This feels wrong. Isn't the idea that only removable drives are auto-selected?

**Comment by alexandrosm** [comment]
I certainly thing system drives should go to the bottom, and potentially
should be grayed out and need a special checkbox/modal to be selected.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
@konmouz 's design already requires the user to explicitly confirm twice before system drives will be written to. Not sure an extra tickbox to 'enable' system drives to be selectable is really necessary? \*shrug\*

**Comment by konmouz** [comment]
@WasabiFan, indeed only removable drives are auto-selected. If only a system drive is available, user will get the 'browse drivers' CTA and has to select it manually.

@alexandrosm, I agree with @lurch. We don't need an extra checkbox to confirm. Currently are notifying user in 4 ways. Red pill label, confirmation with alert icon, alert icon on main Ui page (next to drive) and final confirmation before flashing.

**Comment by alexandrosm** [comment]
fair enough.

How about having system/boot drives at the bottom of the list and somehow
de-emphasised? (grayed out?)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by alexandrosm** [comment]
The other thing to be careful about is the relevant text. Due to the fact
that we're still not 100% on this, we shouldn't say "This is a system
drive, are you sure you want to write to it" but something closer to
"Etcher has identified this as a system drive, are you sure you want to
write to it?". It's a small difference but important to communicate the
level of certainty.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by konmouz** [comment]
Good point, I think we can rephrase. Regarding drives' sorting, I agree that removable disks should be on top and system/boot drives at the bottom. We can try de-emphasising them, the only concern is that they might look appear as unavailable.

**Comment by lurch** [comment]
As discussed [earlier](https://github.com/resin-io/etcher/issues/888#issuecomment-263355732), I guess there'll effectively be three "levels" of drives:
* Drives always writable (Removable drives)
* Drives only writable to after user-confirmation (System drives)
* Drives never writable (Boot drives, Too-small drives, Locked/Read-only drives, Source drives)

IMHO they should be displayed in that order, with the bottom category never selectable, and with drives within each category sorted from smallest-to-largest in terms of capacity.

And I also agree with @alexandrosm 's distinction :+1:

**Comment by Shou** [comment]
What about the behaviour of plugging a removable drive in while Etcher is running? Should that then become the selected drive, if there are only system drives available otherwise?

**Comment by lurch** [comment]
Assuming the user hasn't already specifically selected a drive, then yes. (IIRC it's what the current behaviour does)

**Comment by alexandrosm** [comment]
I like how the hive mind is working here :)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by konmouz** [comment]
Example of list of drives, sorted as discussed (+ overflow).
<img width="923" alt="screen shot 2016-12-02 at 10 53 38" src="https://cloud.githubusercontent.com/assets/15323961/20831712/36f14a32-b87e-11e6-82e4-fdf0ad52f082.png">

Changed to @alexandrosm's suggestion. I am wondering -just to reduce words- if it makes sense to completely remove the question and keep only "Etcher has identified this as a system drive.", since we do make clear that this will erase your data in the last stage modal.
<img width="923" alt="screen shot 2016-12-02 at 10 57 47" src="https://cloud.githubusercontent.com/assets/15323961/20831711/36f14a78-b87e-11e6-9617-a46654f5bac1.png">

**Comment by lurch** [comment]
> We can try de-emphasising them, the only concern is that they might look appear as unavailable.

Yeah, "SYSTEM DRIVE" and "BOOT DRIVE" now look equally un-selectable, even though one is and one isn't :-/

> if it makes sense to completely remove the question and keep only "Etcher has identified this as a system drive."

Yeah, that's a good point - clicking "Continue" here doesn't actually write to the drive, so it probably makes sense to only mention "are you sure you want to write to it?" when we're *actually* about to write to the drive. Or we could even make the text say "Warning: Etcher has identified this as a system drive." (would that still fit on a single line?)

**Comment by konmouz** [comment]
We also provide the 'warning icon' so I think it is enough.

**Comment by konmouz** [comment]
Actually it fits, just test it. So it is still an option.

**Comment by WasabiFan** [comment]
How does the warning look if there are enough drives to force scrolling (i.e. They've got the bottom of the list control)?

**Comment by jviotti** [comment]
> I am wondering -just to reduce words- if it makes sense to completely remove the question and keep only "Etcher has identified this as a system drive.", since we do make clear that this will erase your data in the last stage modal.

I'm all for reducing the amount of modals we use!

**Comment by konmouz** [comment]
<img width="923" alt="screen shot 2016-12-02 at 16 52 28" src="https://cloud.githubusercontent.com/assets/15323961/20842553/cf092020-b8af-11e6-9db6-0a8944289604.png">

**Comment by WasabiFan** [comment]
Looks good! I think the disabled "boot drive" should be greyed out though.

**Comment by konmouz** [comment]
So you can not select your Boot Drive in any case, is that right? In this case we should also remove the greyed out 'tick' on the right.

**Comment by WasabiFan** [comment]
Yep, I believe that's right.

**Comment by alexandrosm** [comment]
@konmouz -- the interaction as designed implies there will only be one
drive selected, which will change with multi-write. Any ideas for how to
alter this to not insert the single-drive assumption?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
@konmouz Nice idea on removing the 'tick' for boot / locked drives :+1: 

For multi-writes I guess we could change the text to something like "Warning: Etcher has identified some of the drives you've selected as system drives." ?

**Comment by alexandrosm** [comment]
yeah, something of that type.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by konmouz** [comment]
@alexandrosm, regarding multi-writes, we might need to alter the modal or the whole UI. The drives space is two small for this purpose. Image selecting 10 drive, it is very difficult to have an overview of your selections.

**Comment by alexandrosm** [comment]
We should seriously consider what that new modal would look like and try to
see if we can make our modifications go in that direction, as I'd hate to
have to re-do a bunch of stuff when we get there.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by konmouz** [comment]
Sure, I'll prepare some sketches.

**Comment by konmouz** [comment]
![screen shot 2016-12-05 at 11 34 36](https://cloud.githubusercontent.com/assets/15323961/20883579/dde90584-bade-11e6-905d-d07b06301cc9.png)

**Comment by lurch** [comment]
While Etcher only supports writing to one drive I wonder if it makes sense to keep the current scrollable-list UI, and when Etcher switches to supporting multiple drives perhaps we could switch to using a 2D grid-layout (instead of a 1D list) so that all the drives are visible at once, without having to scroll?

**Comment by alexandrosm** [comment]
on a somewhat-related note, doesn't it feel like the green tick should be
on the left of the drive name etc?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by alexandrosm** [comment]
and maybe "continue" should be "select these 2 drives"?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment]
Something else I've been meaning to suggest / ask for ages, but keep forgetting to:
Does it "make sense" that while the drive-selection modal is open, changes made in the modal are **instantly** reflected in the parent Etcher window visible behind the modal (e.g. the "Flash" button changing state)? Would it be better if the parent Etcher window only updated once the "Continue" button had been clicked on? (this is similar to https://github.com/resin-io/etcher/issues/729#issuecomment-256057600 )

**Comment by konmouz** [comment]
Agree with both @alexandrosm's and @lurch's points.

**Comment by konmouz** [comment]
Update:
- Tick on the LHS
- 'Select drives (amount of drives)' CTA and 'Available (or detected) drives' as modal window name
- I tried to de-emphasize the system drives (I think they still look selectable, especially compared to the boot drive that has no tick available and also is greyed out)
- If drive's directory is too long, we can use a tooltip

<img width="923" alt="screen shot 2016-12-06 at 13 36 55" src="https://cloud.githubusercontent.com/assets/15323961/20927389/455ee3f2-bbb9-11e6-812b-651d2332c318.png">

**Comment by WasabiFan** [comment]
My initial feeling on this one is that the nuanced grey shades won't be clearly distinct to all users (not just normal ones, but visually impaired ones too and people with low-contrast/brightness displays). It took me a bit to figure out what was going on (although to be fair I'm so tired I lost my phone in my own hand).

**Comment by konmouz** [comment]
I see your point. In addition, since we have a bold visual warning when selecting a system drive, I am not sure if it really worth trying to de-emphasize them.

**Comment by jviotti** [comment]
@konmouz 

> Just to be clear, is the multiple drive selection a feature for the current version or for v.1?
(For v.1 I am exploring a modal window free approach)

This will come after v1. Is a "nice to have" for v1, but I doubt we'll ship with it, since there are still some technical details to sort out.

**Comment by lurch** [comment]
> Just to be clear, is the multiple drive selection a feature for the current version or for v.1?

Current version of Etcher only supports selecting a single drive at a time. When we _do_ have multiple drive selection, for the case where the user has only ticked one drive, would the button say "Select drive" or "Select drives (1)" ?

Hmm, that leads on to another interesting question: When Etcher supports writing to multiple drives at once, will that feature *always* be available (it might be confusing for newbies to accidentally select multiple drives, instead of automatically unselecting the previously-selected drive?), or would it only be available after enabling it in the settings screen?

Agreed the the labelling on the boot drive in the last image is possibly too-light of a grey.

@konmouz Only a small feature, but could you re-order the drives in that last image so that the Removable Drives are ordered smallest (8.0GB) to biggest (120.8GB) ?

**Comment by konmouz** [comment]
`Current version of Etcher only supports selecting a single drive at a time. When we do have multiple drive selection, for the case where the user has only ticked one drive, would the button say "Select drive" or "Select drives (1)" ?`

"Select drives (1)" would be better, since it always implies multi-selection

`Hmm, that leads on to another interesting question: When Etcher supports writing to multiple drives at once, will that feature always be available (it might be confusing for newbies to accidentally select multiple drives, instead of automatically unselecting the previously-selected drive?), or would it only be available after enabling it in the settings screen?`

We can use the same functionality with Gdrive's list view.

`Only a small feature, but could you re-order the drives in that last image so that the Removable Drives are ordered smallest (8.0GB) to biggest (120.8GB) ?`

No problem

**Comment by lurch** [comment]
> > When Etcher supports writing to multiple drives at once, will that feature always be available, or would it only be available after enabling it in the settings screen?

> We can use the same functionality with Gdrive's list view.

Not sure what you mean there (not being a Gdrive user) - could you post some screenshots? :)

**Comment by konmouz** [comment]
Check this video:
https://www.youtube.com/watch?v=ZxAZfs4dqLs

**Comment by jviotti** [comment]
> Only a small feature, but could you re-order the drives in that last image so that the Removable Drives are ordered smallest (8.0GB) to biggest (120.8GB) ?

What is the advantage of re-ordering by size?

**Comment by lurch** [comment]
Ah-ha! The classic Shift-select / Ctrl-select technique (which nearly all file-managers use, not just limited to GDrive).

I'm not sure how well that would work when selecting multiple items out of a scrollable list though? Might be too easy to click-select (and therefore unselecting previously-selected drives that are scrolled out of view) instead of shift-selecting? I'd been expecting that when Etcher supports multi-drive-selection, it'd work like a traditional tickbox-list, i.e. click a drive to select it, click it again to unselect it.

Whereas at the moment (with just single-drive selection) it works like a traditional radiobox-list.

I may be barking up the wrong tree, but I think newbies would expect Etcher to work in a radiobox-list fashion (as it does now), and it's only advanced users who'll want to use multi-drive-selection, and they'll probably want it to work in a tickbox-list fashion (rather than shift-selecting), which is why I was suggesting there might need to be a settings-button to change the modes?

Sorry for rambling...

**Comment by lurch** [comment]
> What is the advantage of re-ordering by size?

a) Always nice to have a persistent sort-mode, rather than having the drives appearing in a random order each time you start the application
b) I was thinking that a user is more likely to want to flash an image onto their 8GB SD card, than it is they'll want to flash an image to their 500GB removable harddrive? Therefore it probably makes sense to move the most-likely option (which I'm assuming is smallest drive) to the top of the list?

**Comment by lurch** [comment]
...and just to clarify, I'm only suggesting displaying removable-drives (smallest to largest), then system-drives (smallest to largest) and finally boot-drives (smallest to largest), and **not** sorting by size regardless of the 'type' of a drive ;-)

**Comment by Shou** [comment]
Should an external HDD count as some sort of protected drive as well? I think it's safe to assume that users generally don't want to write to a medium that is usually used for backups. I swear this was discussed during the summit but I can't find any issues pertaining to it.

Anyway I should probably have a PR up with some preliminary changes for this issue soon today.

**Comment by lurch** [comment]
But I guess it may be hard to tell the difference between a small external HDD, and a large SD card or large USB flash drive? (if it just appears as a generic "USB Mass Storage Device")

**Comment by Shou** [comment]
We could potentially make the assumption that if it's very large even an SD card or flash drive is most likely a backup medium, and treat it as protected too. The only obvious problem I see with this is when users want to write to many such cards the warning modals could get annoying, but that could be mitigated by the multi-write or auto-write functionality.

**Comment by lurch** [comment]
I guess you're effectively proposing an additional "large drive" category, which would work in a similar way to the design for "system drive" above, i.e. display a modal asking something like "The drive you're about to write is _XX_ GB. Are you sure you want to continue?" before actually writing to the drive?

Always tricky to know where to draw that "large drive" boundary though... :-/

**Comment by jviotti** [comment]
> Always tricky to know where to draw that "large drive" boundary though... :-/

Yeah, I propose to stick with that the operating system says and try to have as few heuristics as possible here.

**Comment by konmouz** [comment]
It would be nice to prevent user from accidentally flashing a backup drive, however we can't use too many labels and alerts. Users will just ignore them after a point. At the moment, we have a clear distinction of removable drives (free to flash), system drives (alert to flash) and boot drives (can't flash).

**Comment by lurch** [comment]
...and there's also readonly drives and too-small drives, which are (can't flash) too.

**Comment by konmouz** [comment]
>...and there's also readonly drives and too-small drives, which are (can't flash) too.

and locked SD cards

**Comment by lurch** [comment]
Yeah, I was including "locked SD cards" inside "readonly drives" :)
I agree it makes sense for all (can't flash) drives to be treated the same as the "boot drives" in the earlier UI/UX discussions.
(with the obvious exception that if the user chooses a smaller image, a drive that was previously too small _may_ now be big enough)

**Comment by konmouz** [comment]
@jviotti can we find out the percentage of users that do flash a system drive?

**Comment by jviotti** [comment]
We don't have any directly available data for that sadly, given that we don't send data about drives (whether they are a system one or not, etc) apart from the size.

We plan to do this at some point (for drive usage analytics), but it needs to be done carefully, since it could annoy some people. I know our current analytics model kinda suck, which affects your UX decision making process, so maybe we should start prioritizing that.

In any case, flashing to a system drive usually signals that we didn't detect a drive type correctly (since flashing to a real system drive makes no sense except in incredibly particular cases), so I'm pretty sure the number is quite low.

**Comment by jviotti** [comment]
We should also allow users to bypass any size checks and only flash the amount of data that fits the drive, like `dd` does, which is particularly useful for re flashing backed up images that contain a lot of unnecessary right padding. 

Maybe an "ignore, proceed anyway" message somewhere?

**Comment by konmouz** [comment]
...for reference, I am posting Etcher v02 behaviour.

![screen shot 2017-08-15 at 12 12 14](https://user-images.githubusercontent.com/15323961/29313762-39ef3984-81b3-11e7-8531-ee51c4a83472.png)

![screen shot 2017-08-15 at 12 12 20](https://user-images.githubusercontent.com/15323961/29313761-39e66642-81b3-11e7-92a7-2fb4d6b0985c.png)
